sudo: false
dist: bionic
language: ruby
before_install:
  - gem install bundler
notifications:
  email:
    - jon.pascoe@me.com
branches:
  only:
    - master
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.8
  - 2.7.4
  - 3.0.2
env:
  - RAILS_VERSION='~> 5.2'
  - RAILS_VERSION='~> 6.0'
matrix:
  exclude:
    # Rails 5 does not support Ruby 3.0 and above
    - rvm: 3.0.2
      env: RAILS_VERSION='~> 5.0'

    # Rails 6 supports Ruby 2.5 and above
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 6.0'
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 6.0'
    - rvm: 2.4.5
      env: RAILS_VERSION='~> 6.0'
