on:
  push:
    branches:
      - '**'
name: Ice_Cubed CI
jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    container: ruby:3.0.2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle install --jobs=4 --retry=3
      - name: Run tests
        run: bundle exec rake

