on:
  push:
    branches:
      - '**'
name: Ice_Cubed CI
jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0', jruby, truffleruby]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
